function params = defaultPlotModePDF()
params = {"Figure.WindowState"   , "maximized", ...
          "Figure.Color"         , "w", ...
          "*.LineWidth"          , 0.3, ...
          "*.MarkerSize"         , 1, ...
          "*.SizeData"           , 1, ...
          "Axes.TickDir"         , "out", ...
          "Axes.TickLength"      , [0.02, 0.01], ...
          "Axes.LineWidth"       , 0.3, ...
          "Axes.Box"             , "off", ...
          "Axes.XColor"          , [0, 0, 0], ...
          "Axes.YColor"          , [0, 0, 0], ...
          "Axes.Title.Color"     , [0, 0, 0], ...
          "Axes.Layer"           , "top", ...
          "*.FontName"           , "Arial", ...
          "*.FontSize"           , 8, ...
          "*.FontWeight"         , "normal", ...
          "Axes.XTickLabelRotationMode", "manual", ...
          "Axes.YTickLabelRotationMode", "manual"};
end