function params = defaultPlotModePDF()
params = {"FigureWindowState"  , "maximized", ...
          "FigureColor"        , "w", ...
          "LineLineWidth"      , 0.3, ...
          "LineMarkerSize"     , 1, ...
          "PatchLineWidth"     , 0.3, ...
          "ScatterLineWidth"   , 0.3, ...
          "ScatterSizeData"    , 1, ...
          "AxesTickDir"        , "out", ...
          "AxesTickLength"     , [0.02, 0.01], ...
          "FontName"           , "Arial", ...
          "AxesFontSize"       , 8, ...
          "AxesFontWeight"     , "normal", ...
          "AxesTitleFontWeight", "normal", ...
          "AxesBox"            , "off", ...
          "AxesLineWidth"      , 0.3, ...
          "AxesXColor"         , [0, 0, 0], ...
          "AxesYColor"         , [0, 0, 0], ...
          "AxesLayer"          , "top"};
end