%% demo_subplot
% Demonstration of mu.subplot.
%
% This demo covers:
%   1. H5/CSS-like margins and paddings
%   2. Spanning index in manual-position mode
%   3. Parent as tiledlayout
%   4. PositionType in manual-position mode
%
% Requirements:
%   - Updated mu.subplot supporting:
%       index = [rowStart, colStart, rowSpan, colSpan]
%       indexMode = "linear" | "subscript" | "span" | "auto"
%       Parent = tiledlayout object
%       PositionType = "position" | "outerposition"

ccc;

oldDefaultAxesBox = get(0, "DefaultAxesBox");
cleanupObj = onCleanup(@() set(0, "DefaultAxesBox", oldDefaultAxesBox));

set(0, "DefaultAxesBox", "on");

%% Colors for annotation

C.margin  = [0.85, 0.20, 0.10];
C.padding = [0.10, 0.35, 0.85];
C.grid    = [0.20, 0.20, 0.20];
C.span    = [0.10, 0.60, 0.25];
C.tile    = [0.55, 0.25, 0.75];
C.outer   = [0.95, 0.55, 0.10];

%% Demo 1: H5/CSS-like margins and paddings

fig1 = figure( ...
    "Name", "mu.subplot demo 1: margins and paddings", ...
    "WindowState", "maximized");

margins  = [1/9, 1/18, 2/9, 1/9];   % [left, right, bottom, top], relative to figure
padding1 = [1/5, 1/2, 1/6, 1/6];    % [left, right, bottom, top], relative to div
padding2 = zeros(1, 4);

% div1
[div1Ax, div1Opts] = mu.subplot(fig1, 1, 2, 1, ...
    "margins", margins, ...
    "shape", "fill");
text(div1Ax, 0.05, 0.95, "div1", "Color", "r", "FontWeight", "bold");
local_prepareBoxAxes(div1Ax);

% ax1
[ax1, ax1Opts] = mu.subplot(fig1, 1, 2, 1, ...
    "margins", margins, ...
    "paddings", padding1);
text(ax1, 0.05, 0.95, "ax1", "Color", "r", "FontWeight", "bold");
title(ax1, "paddings create inner space inside div1");

% div2
[div2Ax, div2Opts] = mu.subplot(fig1, 1, 2, 2, ...
    "margins", margins, ...
    "shape", "fill");
text(div2Ax, 0.05, 0.95, "div2", "Color", "r", "FontWeight", "bold");
local_prepareBoxAxes(div2Ax);

% ax2
[ax2, ax2Opts] = mu.subplot(fig1, 1, 2, 2, ...
    "margins", margins, ...
    "paddings", padding2, ...
    "nSize", [1/4, 1/2], ...
    "alignment", "left-bottom");
text(ax2, 0.05, 0.95, "ax2", "Color", "r", "FontWeight", "bold");
title(ax2, "nSize + alignment inside div2");

local_annotateBoxModel(fig1, div1Opts, div2Opts, ax1Opts, C);

%% Demo 2: Spanning index in manual-position mode

fig2 = figure( ...
    "Name", "mu.subplot demo 2: spanning index", ...
    "WindowState", "maximized");

row = 3;
col = 4;

margins2  = [0.06, 0.04, 0.08, 0.07];
paddings2 = [0.08, 0.05, 0.10, 0.08];

% Explicit spanning index: [rowStart, colStart, rowSpan, colSpan]
[axSpan1, optsSpan1] = mu.subplot(fig2, row, col, [1, 1, 2, 2], ...
    "margins", margins2, ...
    "paddings", paddings2, ...
    "indexMode", "span", ...
    "divBox", "show");
plot(axSpan1, rand(20, 1), "LineWidth", 1.4);
title(axSpan1, "index = [1, 1, 2, 2], indexMode = ""span""");

% Backward-compatible subscript index: [row, col]
[axSingle, optsSingle] = mu.subplot(fig2, row, col, [1, 4], ...
    "margins", margins2, ...
    "paddings", paddings2);
bar(axSingle, rand(1, 5));
title(axSingle, "index = [1, 4] as [row, col]");

% Linear vector spanning index. In a 3-by-4 grid, [8, 12] is row 2:3, col 4.
[axSpan2, optsSpan2] = mu.subplot(fig2, row, col, [8, 12], ...
    "margins", margins2, ...
    "paddings", paddings2, ...
    "indexMode", "linear", ...
    "divBox", "show");
imagesc(axSpan2, rand(20));
axis(axSpan2, "image");
title(axSpan2, "index = [8, 12], indexMode = ""linear""");

% Another normal tile
[axNormal, optsNormal] = mu.subplot(fig2, row, col, 7, ...
    "margins", margins2, ...
    "paddings", paddings2);
plot(axNormal, sin(linspace(0, 2*pi, 100)), "LineWidth", 1.4);
title(axNormal, "index = 7");

sgtitle(fig2, "mu.subplot spanning index in manual-position mode");

local_annotateSpanning(fig2, optsSpan1, optsSpan2, optsSingle, optsNormal, C);

%% Demo 3: Parent as tiledlayout

fig3 = figure( ...
    "Name", "mu.subplot demo 3: tiledlayout parent", ...
    "WindowState", "maximized");

t = tiledlayout(fig3, 3, 4, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

title(t, "mu.subplot with tiledlayout parent");

drawnow;

% In tiledlayout mode, mu.subplot delegates layout to nexttile.
% margins/paddings/nSize/shape/alignment are parsed but not applied.

[tx1, topts1] = mu.subplot(t, 3, 4, [1, 1, 2, 2], ...
    "indexMode", "span");
plot(tx1, cumsum(randn(100, 3)), "LineWidth", 1.2);
title(tx1, "tiledlayout: [1, 1, 2, 2]");

[tx2, topts2] = mu.subplot(t, 3, 4, [1, 4]);
bar(tx2, rand(1, 6));
title(tx2, "tiledlayout: [1, 4]");

[tx3, topts3] = mu.subplot(t, 3, 4, [8, 12], ...
    "indexMode", "linear");
imagesc(tx3, peaks(30));
axis(tx3, "image");
title(tx3, "tiledlayout: [8, 12], linear");

[tx4, topts4] = mu.subplot(t, 3, 4, 10);
plot(tx4, rand(10, 1), "-o", "LineWidth", 1.2);
title(tx4, "tiledlayout: index = 10");

local_annotateTiledLayout(fig3, t, ...
    {tx1, tx2, tx3, tx4}, ...
    {topts1, topts2, topts3, topts4}, ...
    C);


%% Demo 4: PositionType in manual-position mode

fig4 = figure( ...
    "Name", "mu.subplot demo 4: PositionType", ...
    "WindowState", "maximized");

margins4  = [0.07, 0.05, 0.14, 0.08];
paddings4 = [0.10, 0.10, 0.16, 0.14];

x = linspace(0, 2*pi, 200);

% Old behavior:
%   Computed target box -> ax.Position.
%   xlabel/ylabel/title/tick labels may extend outside the target box.
[axP, optsP] = mu.subplot(fig4, 1, 2, 1, ...
    "margins", margins4, ...
    "paddings", paddings4, ...
    "PositionType", "position");
plot(axP, x, sin(x), "LineWidth", 1.3);
title(axP, "PositionType = ""position""");
xlabel(axP, "Long xlabel: decorations can grow outside the computed target box");
ylabel(axP, "Long ylabel");
grid(axP, "on");

% New behavior:
%   Computed target box -> ax.OuterPosition.
%   MATLAB shrinks ax.Position so decorations stay inside the target box.
[axO, optsO] = mu.subplot(fig4, 1, 2, 2, ...
    "margins", margins4, ...
    "paddings", paddings4, ...
    "PositionType", "outerposition");
plot(axO, x, cos(x), "LineWidth", 1.3);
title(axO, "PositionType = ""outerposition""");
xlabel(axO, "Long xlabel: decorations are constrained by ax.OuterPosition");
ylabel(axO, "Long ylabel");
grid(axO, "on");

drawnow;
pause(0.05);
drawnow;

local_annotatePositionType(fig4, axP, optsP, axO, optsO, C);

annotation(fig4, "textbox", [0.10, 0.015, 0.80, 0.030], ...
    "String", "PositionType controls which axes box receives the computed target rectangle: target -> ax.Position (left) or target -> ax.OuterPosition (right).", ...
    "Color", C.grid, ...
    "EdgeColor", C.grid, ...
    "BackgroundColor", "w", ...
    "FontWeight", "bold", ...
    "HorizontalAlignment", "center");

%% Local helper functions
function local_annotatePositionType(fig, axP, optsP, axO, optsO, C)
%LOCAL_ANNOTATEPOSITIONTYPE Annotate PositionType behavior.
%
% Green dashed box  : computed target box from mu.subplot
% Blue solid box    : live ax.Position
% Orange dotted box : live ax.OuterPosition

drawnow;
pause(0.05);
drawnow;

local_annotatePositionTypeOne(fig, axP, optsP, ...
    "left: target assigned to ax.Position", C, "northwest");

local_annotatePositionTypeOne(fig, axO, optsO, ...
    "right: target assigned to ax.OuterPosition", C, "northwest");

annotation(fig, "textbox", [0.22, 0.92, 0.56, 0.03], ...
    "String", sprintf(['Legend:  green dashed = computed target box  |  ', ...
                       'blue solid = live ax.Position  |  ', ...
                       'orange dotted = live ax.OuterPosition']), ...
    "Color", C.grid, ...
    "EdgeColor", C.grid, ...
    "BackgroundColor", "w", ...
    "HorizontalAlignment", "center", ...
    "FontWeight", "bold");
end

function local_annotatePositionTypeOne(fig, ax, opts, titleText, C, anchor)
%LOCAL_ANNOTATEPOSITIONTYPEONE Annotate one axes for PositionType demo.

targetPos = local_getOptPosition(opts, "axesTargetPosition", "axesPosition");
[pos, outerPos] = local_getLiveAxesPositions(ax);

local_rectWithLabel(fig, targetPos, ...
    "computed target box", C.span, anchor, "--", 1.8);

local_rectWithLabel(fig, pos, ...
    "live ax.Position", C.padding, "southeast", "-", 1.4);

local_rectWithLabel(fig, outerPos, ...
    "live ax.OuterPosition", C.outer, "southwest", ":", 1.8);

% Panel title note, placed above target box.
targetPos = local_clipNormPos(targetPos);
annotation(fig, "textbox", ...
    [targetPos(1), min(targetPos(2) + targetPos(4) + 0.050, 0.94), targetPos(3), 0.04], ...
    "String", titleText, ...
    "Color", C.grid, ...
    "EdgeColor", "none", ...
    "BackgroundColor", "w", ...
    "HorizontalAlignment", "center", ...
    "FontWeight", "bold");
end

function pos = local_getOptPosition(opts, primaryName, fallbackName)
%LOCAL_GETOPTPOSITION Get a position field from opts with fallback.

if isfield(opts, primaryName) && ~isempty(opts.(primaryName))
    pos = opts.(primaryName);
elseif isfield(opts, fallbackName) && ~isempty(opts.(fallbackName))
    pos = opts.(fallbackName);
else
    error("Cannot find position field '%s' or '%s' in opts.", primaryName, fallbackName);
end
end

function [pos, outerPos] = local_getLiveAxesPositions(ax)
%LOCAL_GETLIVEAXESPOSITIONS Get live axes Position and OuterPosition.

oldUnits = ax.Units;
ax.Units = "normalized";
pos = ax.Position;
outerPos = ax.OuterPosition;
ax.Units = oldUnits;

pos = local_clipNormPos(pos);
outerPos = local_clipNormPos(outerPos);
end

function local_rectWithLabel(fig, pos, label, color, anchor, lineStyle, lineWidth)
%LOCAL_RECTWITHLABEL Draw a rectangle with a nearby label.

pos = local_clipNormPos(pos);

annotation(fig, "rectangle", pos, ...
    "Color", color, ...
    "LineStyle", lineStyle, ...
    "LineWidth", lineWidth);

local_labelNearBox(fig, pos, label, color, anchor);
end

function local_labelNearBox(fig, pos, label, color, anchor)
%LOCAL_LABELNEARBOX Add a label near a rectangle.

pos = local_clipNormPos(pos);

switch lower(string(anchor))
    case "northwest"
        textPos = [pos(1), min(pos(2) + pos(4) + 0.006, 0.95), 0.28, 0.04];
        hAlign = "left";

    case "northeast"
        textPos = [max(pos(1) + pos(3) - 0.28, 0.01), min(pos(2) + pos(4) + 0.006, 0.95), 0.28, 0.04];
        hAlign = "right";

    case "southwest"
        textPos = [pos(1), max(pos(2) - 0.046, 0.01), 0.28, 0.04];
        hAlign = "left";

    case "southeast"
        textPos = [max(pos(1) + pos(3) - 0.28, 0.01), max(pos(2) - 0.046, 0.01), 0.28, 0.04];
        hAlign = "right";

    otherwise
        textPos = [pos(1), min(pos(2) + pos(4) + 0.006, 0.95), 0.28, 0.04];
        hAlign = "left";
end

annotation(fig, "textbox", textPos, ...
    "String", label, ...
    "Color", color, ...
    "EdgeColor", "none", ...
    "BackgroundColor", "w", ...
    "HorizontalAlignment", hAlign, ...
    "FontWeight", "bold");
end


function local_prepareBoxAxes(ax)
%LOCAL_PREPAREBOXAXES Make a div-box axes look like a layout container.

set(ax, ...
    "XLim", [0, 1], ...
    "YLim", [0, 1], ...
    "XTick", [], ...
    "YTick", [], ...
    "Color", "none", ...
    "LineWidth", 1.2);
end

function local_annotateBoxModel(fig, div1Opts, div2Opts, ax1Opts, C)
%LOCAL_ANNOTATEBOXMODEL Add annotations for margins and paddings.

drawnow;

div1 = div1Opts.divPosition;
div2 = div2Opts.divPosition;
ax1  = ax1Opts.axesPosition;
grid = [ ...
    div1Opts.margins(1), ...
    div1Opts.margins(3), ...
    1 - div1Opts.margins(1) - div1Opts.margins(2), ...
    1 - div1Opts.margins(3) - div1Opts.margins(4)];

margins = div1Opts.margins;

% Whole figure boundary
annotation(fig, "rectangle", [0.005, 0.005, 0.99, 0.99], ...
    "Color", C.grid, ...
    "LineStyle", ":", ...
    "LineWidth", 1.2);

% Subplot grid boundary
annotation(fig, "rectangle", grid, ...
    "Color", C.margin, ...
    "LineStyle", "--", ...
    "LineWidth", 1.5);

annotation(fig, "textbox", [0.34, 0.91, 0.36, 0.05], ...
    "String", "subplot grid after applying margins", ...
    "Color", C.margin, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center", ...
    "FontWeight", "bold");

% Margin-left
annotation(fig, "doublearrow", ...
    [0.01, margins(1)], ...
    [div1(2) + div1(4) + 0.035, div1(2) + div1(4) + 0.035], ...
    "Color", C.margin, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [0.01, div1(2) + div1(4) + 0.045, margins(1), 0.045], ...
    "String", "margin-left", ...
    "Color", C.margin, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center");

% Margin-right
annotation(fig, "doublearrow", ...
    [div2(1) + div2(3), 0.99], ...
    [div2(2) + div2(4) + 0.035, div2(2) + div2(4) + 0.035], ...
    "Color", C.margin, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [div2(1) + div2(3), div2(2) + div2(4) + 0.045, margins(2), 0.045], ...
    "String", "margin-right", ...
    "Color", C.margin, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center");

% Margin-bottom
annotation(fig, "doublearrow", ...
    [0.045, 0.045], ...
    [0.01, margins(3)], ...
    "Color", C.margin, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [0.055, 0.08, 0.16, 0.045], ...
    "String", "margin-bottom", ...
    "Color", C.margin, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "left");

% Margin-top
annotation(fig, "doublearrow", ...
    [0.045, 0.045], ...
    [div1(2) + div1(4), 0.99], ...
    "Color", C.margin, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [0.055, div1(2) + div1(4) + 0.035, 0.16, 0.045], ...
    "String", "margin-top", ...
    "Color", C.margin, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "left");

annotation(fig, "textbox", [0.12, 0.02, 0.38, 0.06], ...
    "String", "margins: outer space between figure boundary and subplot grid, relative to figure", ...
    "Color", C.margin, ...
    "EdgeColor", C.margin, ...
    "BackgroundColor", "w", ...
    "HorizontalAlignment", "center");

% Draw ax1 drawable region
annotation(fig, "rectangle", ax1, ...
    "Color", C.padding, ...
    "LineStyle", "-", ...
    "LineWidth", 1.5);

% Padding-left
annotation(fig, "doublearrow", ...
    [div1(1), ax1(1)], ...
    [ax1(2) + ax1(4) / 2, ax1(2) + ax1(4) / 2], ...
    "Color", C.padding, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [div1(1), ax1(2) + ax1(4) / 2 + 0.015, ax1(1) - div1(1), 0.045], ...
    "String", "padding-left", ...
    "Color", C.padding, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center");

% Padding-right
annotation(fig, "doublearrow", ...
    [ax1(1) + ax1(3), div1(1) + div1(3)], ...
    [ax1(2) + ax1(4) / 2, ax1(2) + ax1(4) / 2], ...
    "Color", C.padding, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [ax1(1) + ax1(3), ax1(2) + ax1(4) / 2 + 0.015, ...
     div1(1) + div1(3) - ax1(1) - ax1(3), 0.045], ...
    "String", "padding-right", ...
    "Color", C.padding, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center");

% Padding-bottom
annotation(fig, "doublearrow", ...
    [ax1(1) + ax1(3) + 0.025, ax1(1) + ax1(3) + 0.025], ...
    [div1(2), ax1(2)], ...
    "Color", C.padding, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [ax1(1) + ax1(3) + 0.035, div1(2) + 0.015, 0.16, 0.045], ...
    "String", "padding-bottom", ...
    "Color", C.padding, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "left");

% Padding-top
annotation(fig, "doublearrow", ...
    [ax1(1) + ax1(3) + 0.025, ax1(1) + ax1(3) + 0.025], ...
    [ax1(2) + ax1(4), div1(2) + div1(4)], ...
    "Color", C.padding, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [ax1(1) + ax1(3) + 0.035, ax1(2) + ax1(4) + 0.015, 0.14, 0.045], ...
    "String", "padding-top", ...
    "Color", C.padding, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "left");

annotation(fig, "textbox", [0.54, 0.02, 0.39, 0.06], ...
    "String", "paddings: inner space between each div boundary and axes, relative to div", ...
    "Color", C.padding, ...
    "EdgeColor", C.padding, ...
    "BackgroundColor", "w", ...
    "HorizontalAlignment", "center");
end

function local_annotateSpanning(fig, optsSpan1, optsSpan2, optsSingle, optsNormal, C)
%LOCAL_ANNOTATESPANNING Annotate spanning divs and axes.

drawnow;

% Figure boundary
annotation(fig, "rectangle", [0.005, 0.005, 0.99, 0.99], ...
    "Color", C.grid, ...
    "LineStyle", ":", ...
    "LineWidth", 1.2);

local_boxWithLabel(fig, optsSpan1.divPosition, ...
    "span div: row 1:2, col 1:2", C.span, "northwest");

local_boxWithLabel(fig, optsSpan1.axesPosition, ...
    "axes inside span div", C.padding, "southeast");

local_boxWithLabel(fig, optsSpan2.divPosition, ...
    "linear tiles [8,12] -> row 2:3, col 4", C.span, "northeast");

local_boxWithLabel(fig, optsSingle.divPosition, ...
    "[row,col] single tile", C.tile, "southwest");

local_boxWithLabel(fig, optsNormal.divPosition, ...
    "linear scalar tile", C.tile, "southwest");

annotation(fig, "textbox", [0.08, 0.015, 0.84, 0.055], ...
    "String", "Spanning index: index = [rowStart, colStart, rowSpan, colSpan], or use indexMode=""linear"" for linear tile vectors.", ...
    "Color", C.span, ...
    "EdgeColor", C.span, ...
    "BackgroundColor", "w", ...
    "FontWeight", "bold", ...
    "HorizontalAlignment", "center");
end

function local_annotateTiledLayout(fig, t, axList, optsList, C)
%LOCAL_ANNOTATETILEDLAYOUT Add annotations for tiledlayout mode.
%
% In tiledlayout mode, axes positions are controlled by nexttile. Therefore
% annotation rectangles are computed from the actual axes pixel positions.

drawnow;

try
    tPos = local_normPosInFigure(t, fig);
    annotation(fig, "rectangle", tPos, ...
        "Color", C.grid, ...
        "LineStyle", "--", ...
        "LineWidth", 1.4);
catch
    % Some MATLAB versions do not expose a reliable pixel position for
    % tiledlayout. Axes-level annotations below are still useful.
end

for k = 1:numel(axList)
    ax = axList{k};
    opts = optsList{k};

    pos = local_normPosInFigure(ax, fig);

    label = sprintf( ...
        "tileIndex=%d, span=[%d,%d]", ...
        opts.tileIndex, opts.rowSpan, opts.colSpan);

    local_boxWithLabel(fig, pos, label, C.tile, "northeast");
end

annotation(fig, "textbox", [0.08, 0.01, 0.84, 0.03], ...
    "String", "In tiledlayout mode, opts.axesPosition reports MATLAB-managed axes position; opts.divPosition/drawablePosition are empty.", ...
    "Color", C.tile, ...
    "EdgeColor", C.tile, ...
    "BackgroundColor", "w", ...
    "HorizontalAlignment", "center");
end

function local_boxWithLabel(fig, pos, label, color, anchor)
%LOCAL_BOXWITHLABEL Draw rectangle and nearby label.
%
% pos is normalized figure position: [x, y, w, h].

pos = local_clipNormPos(pos);

annotation(fig, "rectangle", pos, ...
    "Color", color, ...
    "LineWidth", 1.5);

switch lower(anchor)
    case "northwest"
        textPos = [pos(1), min(pos(2) + pos(4) + 0.006, 0.95), 0.28, 0.04];
        hAlign = "left";

    case "northeast"
        textPos = [max(pos(1) + pos(3) - 0.28, 0.01), min(pos(2) + pos(4) + 0.006, 0.95), 0.28, 0.04];
        hAlign = "right";

    case "southwest"
        textPos = [pos(1), max(pos(2) - 0.046, 0.01), 0.28, 0.04];
        hAlign = "left";

    case "southeast"
        textPos = [max(pos(1) + pos(3) - 0.28, 0.01), max(pos(2) - 0.046, 0.01), 0.28, 0.04];
        hAlign = "right";

    otherwise
        textPos = [pos(1), min(pos(2) + pos(4) + 0.006, 0.95), 0.28, 0.04];
        hAlign = "left";
end

annotation(fig, "textbox", textPos, ...
    "String", label, ...
    "Color", color, ...
    "EdgeColor", "none", ...
    "BackgroundColor", "w", ...
    "HorizontalAlignment", hAlign, ...
    "FontWeight", "bold");
end

function pos = local_normPosInFigure(obj, fig)
%LOCAL_NORMPOSINFIGURE Get normalized object position in figure coordinates.
%
% annotation uses normalized figure coordinates. For axes inside tiledlayout,
% ax.Position may be layout-managed and not always directly comparable to
% figure coordinates. getpixelposition(..., true) is used first.

drawnow;

oldFigUnits = fig.Units;
fig.Units = "pixels";
figPixelPos = fig.Position;
fig.Units = oldFigUnits;

try
    objPixelPos = getpixelposition(obj, true);
    pos = [ ...
        objPixelPos(1) / figPixelPos(3), ...
        objPixelPos(2) / figPixelPos(4), ...
        objPixelPos(3) / figPixelPos(3), ...
        objPixelPos(4) / figPixelPos(4)];
catch
    % Fallback for objects that do not support getpixelposition.
    oldUnits = obj.Units;
    obj.Units = "normalized";
    pos = obj.Position;
    obj.Units = oldUnits;
end

pos = local_clipNormPos(pos);
end

function pos = local_clipNormPos(pos)
%LOCAL_CLIPNORMPOS Keep annotation position inside figure.

pos = double(pos);

pos(1) = max(min(pos(1), 0.99), 0.01);
pos(2) = max(min(pos(2), 0.99), 0.01);
pos(3) = max(min(pos(3), 0.99 - pos(1)), 0.001);
pos(4) = max(min(pos(4), 0.99 - pos(2)), 0.001);
end