figure("WindowState", "maximized");
set(0, "DefaultAxesBox", "on");

%% Layout parameters
margins  = [1/9, 1/18, 2/9, 1/9];   % [left, right, bottom, top], relative to figure
padding1 = [1/5, 1/2, 1/6, 1/6];    % [left, right, bottom, top], relative to div
padding2 = zeros(1, 4);

%% div1
mu.subplot(1, 2, 1, ...
    "margins", margins, ...
    "shape", "fill");
text(0.05, 0.95, 'div1', 'Color', 'r');

%% ax1
mu.subplot(1, 2, 1, ...
    "margins", margins, ...
    "paddings", padding1);
text(0.05, 0.95, 'ax1', 'Color', 'r');

%% div2
mu.subplot(1, 2, 2, ...
    "margins", margins, ...
    "shape", "fill");
text(0.05, 0.95, 'div2', 'Color', 'r');

%% ax2
mu.subplot(1, 2, 2, ...
    "margins", margins, ...
    "paddings", padding2, ...
    "nSize", [1/4, 1/2], ...
    "alignment", "left-bottom");
text(0.05, 0.95, 'ax2', 'Color', 'r');

%% Annotations for margins and paddings
% annotation uses normalized figure coordinates.
% Therefore, the coordinates below are calculated in the same normalized
% coordinate system as axes Position.

row = 1;
col = 2;

% div size after applying outer margins
divWidth  = (1 - margins(1) - margins(2)) / col;
divHeight = (1 - margins(3) - margins(4)) / row;

% div1 position
div1X = margins(1);
div1Y = margins(3);
div1W = divWidth;
div1H = divHeight;

% div2 position
div2X = margins(1) + divWidth;
div2Y = margins(3);
div2W = divWidth;
div2H = divHeight;

% ax1 position inside div1.
% Because nSize = [1, 1] and alignment = center by default,
% ax1 exactly fills the padded drawable region.
ax1X = div1X + padding1(1) * div1W;
ax1Y = div1Y + padding1(3) * div1H;
ax1W = (1 - padding1(1) - padding1(2)) * div1W;
ax1H = (1 - padding1(3) - padding1(4)) * div1H;

% Colors for annotation only
marginColor  = [0.85, 0.20, 0.10];
paddingColor = [0.10, 0.35, 0.85];
gridColor    = [0.20, 0.20, 0.20];

% Make sure annotation is attached to the current figure
fig = gcf;

%% Figure boundary and subplot-grid boundary
% Whole figure boundary
annotation(fig, "rectangle", [0.005, 0.005, 0.99, 0.99], ...
    "Color", gridColor, ...
    "LineStyle", ":", ...
    "LineWidth", 1.2);

% Subplot grid boundary after applying margins
annotation(fig, "rectangle", ...
    [margins(1), margins(3), 1 - margins(1) - margins(2), 1 - margins(3) - margins(4)], ...
    "Color", marginColor, ...
    "LineStyle", "--", ...
    "LineWidth", 1.4);

annotation(fig, "textbox", [0.37, 0.91, 0.30, 0.05], ...
    "String", "subplot grid after applying margins", ...
    "Color", marginColor, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center", ...
    "FontWeight", "bold");

%% Margin annotations
% left margin
annotation(fig, "doublearrow", ...
    [0.01, margins(1)], ...
    [div1Y + div1H + 0.035, div1Y + div1H + 0.035], ...
    "Color", marginColor, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [0.01, div1Y + div1H + 0.045, margins(1), 0.045], ...
    "String", "margin-left", ...
    "Color", marginColor, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center");

% right margin
annotation(fig, "doublearrow", ...
    [div2X + div2W, 0.99], ...
    [div2Y + div2H + 0.035, div2Y + div2H + 0.035], ...
    "Color", marginColor, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [div2X + div2W, div2Y + div2H + 0.045, margins(2), 0.045], ...
    "String", "margin-right", ...
    "Color", marginColor, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center");

% bottom margin
annotation(fig, "doublearrow", ...
    [0.045, 0.045], ...
    [0.01, margins(3)], ...
    "Color", marginColor, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [0.055, 0.08, 0.12, 0.045], ...
    "String", "margin-bottom", ...
    "Color", marginColor, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "left");

% top margin
annotation(fig, "doublearrow", ...
    [0.045, 0.045], ...
    [div1Y + div1H, 0.99], ...
    "Color", marginColor, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [0.055, div1Y + div1H + 0.035, 0.12, 0.045], ...
    "String", "margin-top", ...
    "Color", marginColor, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "left");

annotation(fig, "textbox", [0.13, 0.02, 0.38, 0.06], ...
    "String", "margins: outer space between figure boundary and subplot grid, relative to figure", ...
    "Color", marginColor, ...
    "EdgeColor", marginColor, ...
    "BackgroundColor", "w", ...
    "HorizontalAlignment", "center");

%% Padding annotations for ax1
% Draw ax1 drawable region
annotation(fig, "rectangle", [ax1X, ax1Y, ax1W, ax1H], ...
    "Color", paddingColor, ...
    "LineStyle", "-", ...
    "LineWidth", 1.4);

% padding-left inside div1
annotation(fig, "doublearrow", ...
    [div1X, ax1X], ...
    [ax1Y + ax1H / 2, ax1Y + ax1H / 2], ...
    "Color", paddingColor, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [div1X, ax1Y + ax1H / 2 + 0.015, ax1X - div1X, 0.045], ...
    "String", "padding-left", ...
    "Color", paddingColor, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center");

% padding-right inside div1
annotation(fig, "doublearrow", ...
    [ax1X + ax1W, div1X + div1W], ...
    [ax1Y + ax1H / 2, ax1Y + ax1H / 2], ...
    "Color", paddingColor, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [ax1X + ax1W, ax1Y + ax1H / 2 + 0.015, div1X + div1W - ax1X - ax1W, 0.045], ...
    "String", "padding-right", ...
    "Color", paddingColor, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "center");

% padding-bottom inside div1
annotation(fig, "doublearrow", ...
    [ax1X + ax1W + 0.025, ax1X + ax1W + 0.025], ...
    [div1Y, ax1Y], ...
    "Color", paddingColor, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [ax1X + ax1W + 0.035, div1Y + 0.015, 0.13, 0.045], ...
    "String", "padding-bottom", ...
    "Color", paddingColor, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "left");

% padding-top inside div1
annotation(fig, "doublearrow", ...
    [ax1X + ax1W + 0.025, ax1X + ax1W + 0.025], ...
    [ax1Y + ax1H, div1Y + div1H], ...
    "Color", paddingColor, ...
    "LineWidth", 1.4);

annotation(fig, "textbox", ...
    [ax1X + ax1W + 0.035, ax1Y + ax1H + 0.015, 0.11, 0.045], ...
    "String", "padding-top", ...
    "Color", paddingColor, ...
    "EdgeColor", "none", ...
    "HorizontalAlignment", "left");

annotation(fig, "textbox", [0.55, 0.02, 0.38, 0.06], ...
    "String", "paddings: inner space between each div boundary and axes, relative to div", ...
    "Color", paddingColor, ...
    "EdgeColor", paddingColor, ...
    "BackgroundColor", "w", ...
    "HorizontalAlignment", "center");

set(0, "DefaultAxesBox", "factory");